# Generated by Django 3.1.7 on 2021-04-17 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bottom_Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bottom_banner')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='brand')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.PositiveIntegerField()),
                ('locality', models.CharField(max_length=200)),
                ('landmark', models.CharField(max_length=200, null=True)),
                ('alternate_mobile', models.IntegerField(null=True)),
                ('order_mode', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_percent', models.FloatField(blank=True, null=True)),
                ('gst_percent', models.FloatField(blank=True, null=True)),
                ('variant', models.CharField(choices=[('Size', 'Size'), ('Color', 'Color'), ('Size-Color', 'Size-Color')], default='Size', max_length=10)),
                ('image', models.ImageField(null=True, upload_to='product')),
                ('status', models.BooleanField(default=False)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brands')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('image_fornt', models.ImageField(null=True, upload_to='image_front')),
                ('image_back', models.ImageField(null=True, upload_to='image_back')),
                ('image_side', models.ImageField(null=True, upload_to='image_side')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weight', models.FloatField(null=True)),
                ('point_value', models.FloatField(null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.size')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_mobile', models.IntegerField()),
                ('vendor_status', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(null=True, upload_to='vendor_profile_pic')),
                ('store_status', models.BooleanField(default=False)),
                ('store_remove', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('utype', models.CharField(default='Vendor', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_Store_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('store_address', models.CharField(max_length=200, null=True)),
                ('store_zipcode', models.CharField(max_length=20, null=True)),
                ('store_latitude', models.CharField(max_length=200, null=True)),
                ('store_longitude', models.CharField(max_length=200, null=True)),
                ('store_description', models.TextField()),
                ('store_registration_number', models.CharField(max_length=100, null=True)),
                ('store_category', models.CharField(max_length=200)),
                ('store_logo', models.ImageField(upload_to='store_logo')),
                ('store_banner', models.ImageField(upload_to='store_banner')),
                ('store_image', models.ImageField(upload_to='store_image')),
                ('store_closing_day', models.CharField(max_length=200)),
                ('store_closing_time', models.CharField(max_length=20)),
                ('store_opening_time', models.CharField(max_length=20)),
                ('store_created_at', models.DateTimeField(auto_now_add=True)),
                ('store_update_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vendor_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendor_store_detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.variants')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_store_document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_seller_aadhar', models.IntegerField()),
                ('store_seller_gst', models.CharField(max_length=100)),
                ('store_seller_front_aadhar_image', models.FileField(upload_to='store_seller_aadhar_image')),
                ('store_seller_back_aadhar_image', models.FileField(null=True, upload_to='store_seller_aadhar_image')),
                ('store_seller_pancard', models.CharField(max_length=100)),
                ('store_seller_pancard_image', models.FileField(upload_to='store_seller_pancard_image')),
                ('store_shiping_policy', models.FileField(null=True, upload_to='shiping_policy')),
                ('store_return_policy', models.FileField(null=True, upload_to='return_policy')),
                ('store_bank_account_number', models.CharField(max_length=300)),
                ('store_bank_name', models.CharField(max_length=100)),
                ('store_bank_ifsc', models.CharField(max_length=100)),
                ('store_bank_passbook', models.FileField(upload_to='store_bank_passbook')),
                ('store_seller_razorpay_id', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('final_price', models.FloatField(default='0.0')),
                ('cart_status', models.BooleanField(default=False)),
                ('store_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendor_store_detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.variants')),
            ],
        ),
        migrations.CreateModel(
            name='User_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('gender', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50, null=True)),
                ('longitude', models.CharField(max_length=50, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('otp', models.CharField(max_length=20, null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='profile_pic')),
                ('utype', models.CharField(default='User', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='subcategory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Refer_id_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer_code', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refer_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refercode', models.CharField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='random_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PVset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PV', models.FloatField()),
                ('Subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='stor_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendor_store_detail'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=200)),
                ('order_id', models.CharField(max_length=200)),
                ('signature', models.CharField(max_length=200)),
                ('order_status', models.BooleanField(default=False)),
                ('delivery_status', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('time_slot', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField()),
                ('delivery_address', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.delivery_address')),
                ('item', models.ManyToManyField(to='app.UserCart')),
                ('store_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendor_store_detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.URLField(blank=True, max_length=6000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.AddField(
            model_name='brands',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategory'),
        ),
    ]
