# Generated by Django 3.1.7 on 2021-04-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='order_status',
            field=models.CharField(choices=[('Confirm', 'Confirm'), ('Booked', 'Booked'), ('Cancel', 'Cancel')], default='Booked', max_length=100),
        ),
    ]
