# Generated by Django 3.1.7 on 2021-04-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_detail_cancel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='order_mode',
            field=models.CharField(choices=[('Self_Picking', 'Self_Pickig'), ('Delivery', 'Delivery')], default='Order', max_length=40),
        ),
    ]
