# Generated by Django 3.1.7 on 2021-04-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210421_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='update_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
