# Generated by Django 3.1.7 on 2021-04-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_variants_variant_show_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='update_date_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='update_date_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery_address',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='random_address',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='refer_code',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='refer_code',
            name='update_date_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='refer_id_store',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='update_date_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_register',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user_register',
            name='update_date_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usercart',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usercart',
            name='update_date_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='update_date_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor_registration',
            name='update_date_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor_store_document',
            name='update_date_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
