# Generated by Django 3.1.7 on 2021-04-22 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_auto_20210421_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_fake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_percent', models.FloatField(blank=True, null=True)),
                ('gst_percent', models.FloatField(blank=True, null=True)),
                ('variant', models.CharField(max_length=10)),
                ('image', models.ImageField(null=True, upload_to='product_fake')),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('stor_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendor_store_detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Variants_fake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('image_fornt', models.ImageField(null=True, upload_to='image_front_fake')),
                ('image_back', models.ImageField(null=True, upload_to='image_back_fake')),
                ('image_side', models.ImageField(null=True, upload_to='image_side_fake')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weight', models.FloatField(null=True)),
                ('point_value', models.FloatField(null=True)),
                ('after_discount_price', models.FloatField(null=True)),
                ('variant_discount', models.FloatField(null=True)),
                ('variant_show_status', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_fake')),
            ],
        ),
    ]
