# Generated by Django 3.1.7 on 2021-04-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_vendor_time_slot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vendor_time_slot',
        ),
    ]
