# Generated by Django 3.1.7 on 2021-04-24 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_delete_vendor_time_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_time_slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.CharField(max_length=100)),
                ('to_time', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendor_store_detail')),
            ],
        ),
    ]
