# Generated by Django 3.1.7 on 2021-04-24 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_vendor_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='brand_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.brands'),
        ),
        migrations.AddField(
            model_name='variants',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
        migrations.AddField(
            model_name='variants',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.subcategory'),
        ),
    ]
