# Generated by Django 3.1.7 on 2021-04-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210425_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='category',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='subcategory',
        ),
    ]
