# Generated by Django 3.1.7 on 2021-04-25 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210425_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='delivery_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.delivery_address'),
        ),
    ]
