# Generated by Django 3.1.7 on 2021-04-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_order_detail_product_fake_variants_fake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery_address',
            old_name='order_mode',
            new_name='house_number',
        ),
    ]
