# Generated by Django 3.1.7 on 2021-04-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210426_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='order_mode',
            field=models.CharField(max_length=40),
        ),
    ]
