# Generated by Django 3.1.7 on 2021-04-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210426_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants_fake',
            name='real_var_id',
            field=models.IntegerField(null=True),
        ),
    ]
