# Generated by Django 3.1.7 on 2021-04-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_variants_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='oreder_cancel_reason',
            field=models.TextField(null=True),
        ),
    ]
