# Generated by Django 3.1.7 on 2021-05-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_treechain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreeChain',
        ),
    ]
