# Generated by Django 3.1.7 on 2021-05-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_direct_refer_statements_pv_earn_by_self'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreeChain',
        ),
    ]
