# Generated by Django 3.1.7 on 2021-05-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_treechain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreeChain',
        ),
    ]
